// Generated by prune.py from the modal 1.6.0 wheel's modal_proto/api.proto
// (Apache-2.0, Copyright Modal Labs; see LICENSE in this directory).
// A subset: only what frontend/modal serves. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: modal_proto/api.proto

package modalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModalClient_AppGetOrCreate_FullMethodName                = "/modal.client.ModalClient/AppGetOrCreate"
	ModalClient_EnvironmentGetOrCreate_FullMethodName        = "/modal.client.ModalClient/EnvironmentGetOrCreate"
	ModalClient_ImageGetOrCreate_FullMethodName              = "/modal.client.ModalClient/ImageGetOrCreate"
	ModalClient_ImageJoinStreaming_FullMethodName            = "/modal.client.ModalClient/ImageJoinStreaming"
	ModalClient_AuthTokenGet_FullMethodName                  = "/modal.client.ModalClient/AuthTokenGet"
	ModalClient_SandboxCreateV2_FullMethodName               = "/modal.client.ModalClient/SandboxCreateV2"
	ModalClient_SandboxGetTaskIdV2_FullMethodName            = "/modal.client.ModalClient/SandboxGetTaskIdV2"
	ModalClient_SandboxGetCommandRouterAccess_FullMethodName = "/modal.client.ModalClient/SandboxGetCommandRouterAccess"
	ModalClient_SandboxWaitV2_FullMethodName                 = "/modal.client.ModalClient/SandboxWaitV2"
	ModalClient_SandboxTerminateV2_FullMethodName            = "/modal.client.ModalClient/SandboxTerminateV2"
	ModalClient_SandboxCreate_FullMethodName                 = "/modal.client.ModalClient/SandboxCreate"
	ModalClient_SandboxGetTaskId_FullMethodName              = "/modal.client.ModalClient/SandboxGetTaskId"
	ModalClient_TaskGetCommandRouterAccess_FullMethodName    = "/modal.client.ModalClient/TaskGetCommandRouterAccess"
	ModalClient_SandboxWait_FullMethodName                   = "/modal.client.ModalClient/SandboxWait"
	ModalClient_SandboxTerminate_FullMethodName              = "/modal.client.ModalClient/SandboxTerminate"
)

// ModalClientClient is the client API for ModalClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModalClientClient interface {
	AppGetOrCreate(ctx context.Context, in *AppGetOrCreateRequest, opts ...grpc.CallOption) (*AppGetOrCreateResponse, error)
	EnvironmentGetOrCreate(ctx context.Context, in *EnvironmentGetOrCreateRequest, opts ...grpc.CallOption) (*EnvironmentGetOrCreateResponse, error)
	ImageGetOrCreate(ctx context.Context, in *ImageGetOrCreateRequest, opts ...grpc.CallOption) (*ImageGetOrCreateResponse, error)
	ImageJoinStreaming(ctx context.Context, in *ImageJoinStreamingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageJoinStreamingResponse], error)
	AuthTokenGet(ctx context.Context, in *AuthTokenGetRequest, opts ...grpc.CallOption) (*AuthTokenGetResponse, error)
	SandboxCreateV2(ctx context.Context, in *SandboxCreateV2Request, opts ...grpc.CallOption) (*SandboxCreateV2Response, error)
	SandboxGetTaskIdV2(ctx context.Context, in *SandboxGetTaskIdRequest, opts ...grpc.CallOption) (*SandboxGetTaskIdResponse, error)
	SandboxGetCommandRouterAccess(ctx context.Context, in *SandboxGetCommandRouterAccessRequest, opts ...grpc.CallOption) (*SandboxGetCommandRouterAccessResponse, error)
	SandboxWaitV2(ctx context.Context, in *SandboxWaitRequest, opts ...grpc.CallOption) (*SandboxWaitResponse, error)
	SandboxTerminateV2(ctx context.Context, in *SandboxTerminateRequest, opts ...grpc.CallOption) (*SandboxTerminateResponse, error)
	SandboxCreate(ctx context.Context, in *SandboxCreateRequest, opts ...grpc.CallOption) (*SandboxCreateResponse, error)
	SandboxGetTaskId(ctx context.Context, in *SandboxGetTaskIdRequest, opts ...grpc.CallOption) (*SandboxGetTaskIdResponse, error)
	TaskGetCommandRouterAccess(ctx context.Context, in *TaskGetCommandRouterAccessRequest, opts ...grpc.CallOption) (*TaskGetCommandRouterAccessResponse, error)
	SandboxWait(ctx context.Context, in *SandboxWaitRequest, opts ...grpc.CallOption) (*SandboxWaitResponse, error)
	SandboxTerminate(ctx context.Context, in *SandboxTerminateRequest, opts ...grpc.CallOption) (*SandboxTerminateResponse, error)
}

type modalClientClient struct {
	cc grpc.ClientConnInterface
}

func NewModalClientClient(cc grpc.ClientConnInterface) ModalClientClient {
	return &modalClientClient{cc}
}

func (c *modalClientClient) AppGetOrCreate(ctx context.Context, in *AppGetOrCreateRequest, opts ...grpc.CallOption) (*AppGetOrCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppGetOrCreateResponse)
	err := c.cc.Invoke(ctx, ModalClient_AppGetOrCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) EnvironmentGetOrCreate(ctx context.Context, in *EnvironmentGetOrCreateRequest, opts ...grpc.CallOption) (*EnvironmentGetOrCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvironmentGetOrCreateResponse)
	err := c.cc.Invoke(ctx, ModalClient_EnvironmentGetOrCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) ImageGetOrCreate(ctx context.Context, in *ImageGetOrCreateRequest, opts ...grpc.CallOption) (*ImageGetOrCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageGetOrCreateResponse)
	err := c.cc.Invoke(ctx, ModalClient_ImageGetOrCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) ImageJoinStreaming(ctx context.Context, in *ImageJoinStreamingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageJoinStreamingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModalClient_ServiceDesc.Streams[0], ModalClient_ImageJoinStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageJoinStreamingRequest, ImageJoinStreamingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModalClient_ImageJoinStreamingClient = grpc.ServerStreamingClient[ImageJoinStreamingResponse]

func (c *modalClientClient) AuthTokenGet(ctx context.Context, in *AuthTokenGetRequest, opts ...grpc.CallOption) (*AuthTokenGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTokenGetResponse)
	err := c.cc.Invoke(ctx, ModalClient_AuthTokenGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxCreateV2(ctx context.Context, in *SandboxCreateV2Request, opts ...grpc.CallOption) (*SandboxCreateV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxCreateV2Response)
	err := c.cc.Invoke(ctx, ModalClient_SandboxCreateV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxGetTaskIdV2(ctx context.Context, in *SandboxGetTaskIdRequest, opts ...grpc.CallOption) (*SandboxGetTaskIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxGetTaskIdResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxGetTaskIdV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxGetCommandRouterAccess(ctx context.Context, in *SandboxGetCommandRouterAccessRequest, opts ...grpc.CallOption) (*SandboxGetCommandRouterAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxGetCommandRouterAccessResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxGetCommandRouterAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxWaitV2(ctx context.Context, in *SandboxWaitRequest, opts ...grpc.CallOption) (*SandboxWaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxWaitResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxWaitV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxTerminateV2(ctx context.Context, in *SandboxTerminateRequest, opts ...grpc.CallOption) (*SandboxTerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxTerminateResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxTerminateV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxCreate(ctx context.Context, in *SandboxCreateRequest, opts ...grpc.CallOption) (*SandboxCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxCreateResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxGetTaskId(ctx context.Context, in *SandboxGetTaskIdRequest, opts ...grpc.CallOption) (*SandboxGetTaskIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxGetTaskIdResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxGetTaskId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) TaskGetCommandRouterAccess(ctx context.Context, in *TaskGetCommandRouterAccessRequest, opts ...grpc.CallOption) (*TaskGetCommandRouterAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGetCommandRouterAccessResponse)
	err := c.cc.Invoke(ctx, ModalClient_TaskGetCommandRouterAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxWait(ctx context.Context, in *SandboxWaitRequest, opts ...grpc.CallOption) (*SandboxWaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxWaitResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxWait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modalClientClient) SandboxTerminate(ctx context.Context, in *SandboxTerminateRequest, opts ...grpc.CallOption) (*SandboxTerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxTerminateResponse)
	err := c.cc.Invoke(ctx, ModalClient_SandboxTerminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModalClientServer is the server API for ModalClient service.
// All implementations must embed UnimplementedModalClientServer
// for forward compatibility.
type ModalClientServer interface {
	AppGetOrCreate(context.Context, *AppGetOrCreateRequest) (*AppGetOrCreateResponse, error)
	EnvironmentGetOrCreate(context.Context, *EnvironmentGetOrCreateRequest) (*EnvironmentGetOrCreateResponse, error)
	ImageGetOrCreate(context.Context, *ImageGetOrCreateRequest) (*ImageGetOrCreateResponse, error)
	ImageJoinStreaming(*ImageJoinStreamingRequest, grpc.ServerStreamingServer[ImageJoinStreamingResponse]) error
	AuthTokenGet(context.Context, *AuthTokenGetRequest) (*AuthTokenGetResponse, error)
	SandboxCreateV2(context.Context, *SandboxCreateV2Request) (*SandboxCreateV2Response, error)
	SandboxGetTaskIdV2(context.Context, *SandboxGetTaskIdRequest) (*SandboxGetTaskIdResponse, error)
	SandboxGetCommandRouterAccess(context.Context, *SandboxGetCommandRouterAccessRequest) (*SandboxGetCommandRouterAccessResponse, error)
	SandboxWaitV2(context.Context, *SandboxWaitRequest) (*SandboxWaitResponse, error)
	SandboxTerminateV2(context.Context, *SandboxTerminateRequest) (*SandboxTerminateResponse, error)
	SandboxCreate(context.Context, *SandboxCreateRequest) (*SandboxCreateResponse, error)
	SandboxGetTaskId(context.Context, *SandboxGetTaskIdRequest) (*SandboxGetTaskIdResponse, error)
	TaskGetCommandRouterAccess(context.Context, *TaskGetCommandRouterAccessRequest) (*TaskGetCommandRouterAccessResponse, error)
	SandboxWait(context.Context, *SandboxWaitRequest) (*SandboxWaitResponse, error)
	SandboxTerminate(context.Context, *SandboxTerminateRequest) (*SandboxTerminateResponse, error)
	mustEmbedUnimplementedModalClientServer()
}

// UnimplementedModalClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModalClientServer struct{}

func (UnimplementedModalClientServer) AppGetOrCreate(context.Context, *AppGetOrCreateRequest) (*AppGetOrCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppGetOrCreate not implemented")
}
func (UnimplementedModalClientServer) EnvironmentGetOrCreate(context.Context, *EnvironmentGetOrCreateRequest) (*EnvironmentGetOrCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnvironmentGetOrCreate not implemented")
}
func (UnimplementedModalClientServer) ImageGetOrCreate(context.Context, *ImageGetOrCreateRequest) (*ImageGetOrCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImageGetOrCreate not implemented")
}
func (UnimplementedModalClientServer) ImageJoinStreaming(*ImageJoinStreamingRequest, grpc.ServerStreamingServer[ImageJoinStreamingResponse]) error {
	return status.Error(codes.Unimplemented, "method ImageJoinStreaming not implemented")
}
func (UnimplementedModalClientServer) AuthTokenGet(context.Context, *AuthTokenGetRequest) (*AuthTokenGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthTokenGet not implemented")
}
func (UnimplementedModalClientServer) SandboxCreateV2(context.Context, *SandboxCreateV2Request) (*SandboxCreateV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxCreateV2 not implemented")
}
func (UnimplementedModalClientServer) SandboxGetTaskIdV2(context.Context, *SandboxGetTaskIdRequest) (*SandboxGetTaskIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxGetTaskIdV2 not implemented")
}
func (UnimplementedModalClientServer) SandboxGetCommandRouterAccess(context.Context, *SandboxGetCommandRouterAccessRequest) (*SandboxGetCommandRouterAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxGetCommandRouterAccess not implemented")
}
func (UnimplementedModalClientServer) SandboxWaitV2(context.Context, *SandboxWaitRequest) (*SandboxWaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxWaitV2 not implemented")
}
func (UnimplementedModalClientServer) SandboxTerminateV2(context.Context, *SandboxTerminateRequest) (*SandboxTerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxTerminateV2 not implemented")
}
func (UnimplementedModalClientServer) SandboxCreate(context.Context, *SandboxCreateRequest) (*SandboxCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxCreate not implemented")
}
func (UnimplementedModalClientServer) SandboxGetTaskId(context.Context, *SandboxGetTaskIdRequest) (*SandboxGetTaskIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxGetTaskId not implemented")
}
func (UnimplementedModalClientServer) TaskGetCommandRouterAccess(context.Context, *TaskGetCommandRouterAccessRequest) (*TaskGetCommandRouterAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskGetCommandRouterAccess not implemented")
}
func (UnimplementedModalClientServer) SandboxWait(context.Context, *SandboxWaitRequest) (*SandboxWaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxWait not implemented")
}
func (UnimplementedModalClientServer) SandboxTerminate(context.Context, *SandboxTerminateRequest) (*SandboxTerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SandboxTerminate not implemented")
}
func (UnimplementedModalClientServer) mustEmbedUnimplementedModalClientServer() {}
func (UnimplementedModalClientServer) testEmbeddedByValue()                     {}

// UnsafeModalClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModalClientServer will
// result in compilation errors.
type UnsafeModalClientServer interface {
	mustEmbedUnimplementedModalClientServer()
}

func RegisterModalClientServer(s grpc.ServiceRegistrar, srv ModalClientServer) {
	// If the following call panics, it indicates UnimplementedModalClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModalClient_ServiceDesc, srv)
}

func _ModalClient_AppGetOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetOrCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).AppGetOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_AppGetOrCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).AppGetOrCreate(ctx, req.(*AppGetOrCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_EnvironmentGetOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvironmentGetOrCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).EnvironmentGetOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_EnvironmentGetOrCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).EnvironmentGetOrCreate(ctx, req.(*EnvironmentGetOrCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_ImageGetOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageGetOrCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).ImageGetOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_ImageGetOrCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).ImageGetOrCreate(ctx, req.(*ImageGetOrCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_ImageJoinStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageJoinStreamingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModalClientServer).ImageJoinStreaming(m, &grpc.GenericServerStream[ImageJoinStreamingRequest, ImageJoinStreamingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModalClient_ImageJoinStreamingServer = grpc.ServerStreamingServer[ImageJoinStreamingResponse]

func _ModalClient_AuthTokenGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).AuthTokenGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_AuthTokenGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).AuthTokenGet(ctx, req.(*AuthTokenGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxCreateV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxCreateV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxCreateV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxCreateV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxCreateV2(ctx, req.(*SandboxCreateV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxGetTaskIdV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxGetTaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxGetTaskIdV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxGetTaskIdV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxGetTaskIdV2(ctx, req.(*SandboxGetTaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxGetCommandRouterAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxGetCommandRouterAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxGetCommandRouterAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxGetCommandRouterAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxGetCommandRouterAccess(ctx, req.(*SandboxGetCommandRouterAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxWaitV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxWaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxWaitV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxWaitV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxWaitV2(ctx, req.(*SandboxWaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxTerminateV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxTerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxTerminateV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxTerminateV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxTerminateV2(ctx, req.(*SandboxTerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxCreate(ctx, req.(*SandboxCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxGetTaskId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxGetTaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxGetTaskId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxGetTaskId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxGetTaskId(ctx, req.(*SandboxGetTaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_TaskGetCommandRouterAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskGetCommandRouterAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).TaskGetCommandRouterAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_TaskGetCommandRouterAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).TaskGetCommandRouterAccess(ctx, req.(*TaskGetCommandRouterAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxWait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxWaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxWait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxWait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxWait(ctx, req.(*SandboxWaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModalClient_SandboxTerminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxTerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModalClientServer).SandboxTerminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModalClient_SandboxTerminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModalClientServer).SandboxTerminate(ctx, req.(*SandboxTerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModalClient_ServiceDesc is the grpc.ServiceDesc for ModalClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModalClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modal.client.ModalClient",
	HandlerType: (*ModalClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppGetOrCreate",
			Handler:    _ModalClient_AppGetOrCreate_Handler,
		},
		{
			MethodName: "EnvironmentGetOrCreate",
			Handler:    _ModalClient_EnvironmentGetOrCreate_Handler,
		},
		{
			MethodName: "ImageGetOrCreate",
			Handler:    _ModalClient_ImageGetOrCreate_Handler,
		},
		{
			MethodName: "AuthTokenGet",
			Handler:    _ModalClient_AuthTokenGet_Handler,
		},
		{
			MethodName: "SandboxCreateV2",
			Handler:    _ModalClient_SandboxCreateV2_Handler,
		},
		{
			MethodName: "SandboxGetTaskIdV2",
			Handler:    _ModalClient_SandboxGetTaskIdV2_Handler,
		},
		{
			MethodName: "SandboxGetCommandRouterAccess",
			Handler:    _ModalClient_SandboxGetCommandRouterAccess_Handler,
		},
		{
			MethodName: "SandboxWaitV2",
			Handler:    _ModalClient_SandboxWaitV2_Handler,
		},
		{
			MethodName: "SandboxTerminateV2",
			Handler:    _ModalClient_SandboxTerminateV2_Handler,
		},
		{
			MethodName: "SandboxCreate",
			Handler:    _ModalClient_SandboxCreate_Handler,
		},
		{
			MethodName: "SandboxGetTaskId",
			Handler:    _ModalClient_SandboxGetTaskId_Handler,
		},
		{
			MethodName: "TaskGetCommandRouterAccess",
			Handler:    _ModalClient_TaskGetCommandRouterAccess_Handler,
		},
		{
			MethodName: "SandboxWait",
			Handler:    _ModalClient_SandboxWait_Handler,
		},
		{
			MethodName: "SandboxTerminate",
			Handler:    _ModalClient_SandboxTerminate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImageJoinStreaming",
			Handler:       _ModalClient_ImageJoinStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "modal_proto/api.proto",
}
