// Generated by prune.py from the modal 1.6.0 wheel's modal_proto/task_command_router.proto
// (Apache-2.0, Copyright Modal Labs; see LICENSE in this directory).
// A subset: only what frontend/modal serves. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: modal_proto/task_command_router.proto

package modalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskExecStderrConfig int32

const (
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_DEVNULL TaskExecStderrConfig = 0
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_PIPE    TaskExecStderrConfig = 1
	TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_STDOUT  TaskExecStderrConfig = 2
)

// Enum value maps for TaskExecStderrConfig.
var (
	TaskExecStderrConfig_name = map[int32]string{
		0: "TASK_EXEC_STDERR_CONFIG_DEVNULL",
		1: "TASK_EXEC_STDERR_CONFIG_PIPE",
		2: "TASK_EXEC_STDERR_CONFIG_STDOUT",
	}
	TaskExecStderrConfig_value = map[string]int32{
		"TASK_EXEC_STDERR_CONFIG_DEVNULL": 0,
		"TASK_EXEC_STDERR_CONFIG_PIPE":    1,
		"TASK_EXEC_STDERR_CONFIG_STDOUT":  2,
	}
)

func (x TaskExecStderrConfig) Enum() *TaskExecStderrConfig {
	p := new(TaskExecStderrConfig)
	*p = x
	return p
}

func (x TaskExecStderrConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStderrConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[0].Descriptor()
}

func (TaskExecStderrConfig) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[0]
}

func (x TaskExecStderrConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskExecStderrConfig.Descriptor instead.
func (TaskExecStderrConfig) EnumDescriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{0}
}

type TaskExecStdioFileDescriptor int32

const (
	TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT TaskExecStdioFileDescriptor = 0
	TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR TaskExecStdioFileDescriptor = 1
)

// Enum value maps for TaskExecStdioFileDescriptor.
var (
	TaskExecStdioFileDescriptor_name = map[int32]string{
		0: "TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT",
		1: "TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR",
	}
	TaskExecStdioFileDescriptor_value = map[string]int32{
		"TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT": 0,
		"TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR": 1,
	}
)

func (x TaskExecStdioFileDescriptor) Enum() *TaskExecStdioFileDescriptor {
	p := new(TaskExecStdioFileDescriptor)
	*p = x
	return p
}

func (x TaskExecStdioFileDescriptor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStdioFileDescriptor) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[1].Descriptor()
}

func (TaskExecStdioFileDescriptor) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[1]
}

func (x TaskExecStdioFileDescriptor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskExecStdioFileDescriptor.Descriptor instead.
func (TaskExecStdioFileDescriptor) EnumDescriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{1}
}

type TaskExecStdoutConfig int32

const (
	TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_DEVNULL TaskExecStdoutConfig = 0
	TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_PIPE    TaskExecStdoutConfig = 1
)

// Enum value maps for TaskExecStdoutConfig.
var (
	TaskExecStdoutConfig_name = map[int32]string{
		0: "TASK_EXEC_STDOUT_CONFIG_DEVNULL",
		1: "TASK_EXEC_STDOUT_CONFIG_PIPE",
	}
	TaskExecStdoutConfig_value = map[string]int32{
		"TASK_EXEC_STDOUT_CONFIG_DEVNULL": 0,
		"TASK_EXEC_STDOUT_CONFIG_PIPE":    1,
	}
)

func (x TaskExecStdoutConfig) Enum() *TaskExecStdoutConfig {
	p := new(TaskExecStdoutConfig)
	*p = x
	return p
}

func (x TaskExecStdoutConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskExecStdoutConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_modal_proto_task_command_router_proto_enumTypes[2].Descriptor()
}

func (TaskExecStdoutConfig) Type() protoreflect.EnumType {
	return &file_modal_proto_task_command_router_proto_enumTypes[2]
}

func (x TaskExecStdoutConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskExecStdoutConfig.Descriptor instead.
func (TaskExecStdoutConfig) EnumDescriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{2}
}

type TaskExecPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecPollRequest) Reset() {
	*x = TaskExecPollRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecPollRequest) ProtoMessage() {}

func (x *TaskExecPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecPollRequest.ProtoReflect.Descriptor instead.
func (*TaskExecPollRequest) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecPollRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecPollRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type TaskExecPollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExitStatus:
	//
	//	*TaskExecPollResponse_Code
	//	*TaskExecPollResponse_Signal
	ExitStatus    isTaskExecPollResponse_ExitStatus `protobuf_oneof:"exit_status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecPollResponse) Reset() {
	*x = TaskExecPollResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecPollResponse) ProtoMessage() {}

func (x *TaskExecPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecPollResponse.ProtoReflect.Descriptor instead.
func (*TaskExecPollResponse) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecPollResponse) GetExitStatus() isTaskExecPollResponse_ExitStatus {
	if x != nil {
		return x.ExitStatus
	}
	return nil
}

func (x *TaskExecPollResponse) GetCode() int32 {
	if x != nil {
		if x, ok := x.ExitStatus.(*TaskExecPollResponse_Code); ok {
			return x.Code
		}
	}
	return 0
}

func (x *TaskExecPollResponse) GetSignal() int32 {
	if x != nil {
		if x, ok := x.ExitStatus.(*TaskExecPollResponse_Signal); ok {
			return x.Signal
		}
	}
	return 0
}

type isTaskExecPollResponse_ExitStatus interface {
	isTaskExecPollResponse_ExitStatus()
}

type TaskExecPollResponse_Code struct {
	Code int32 `protobuf:"varint,1,opt,name=code,proto3,oneof"`
}

type TaskExecPollResponse_Signal struct {
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof"`
}

func (*TaskExecPollResponse_Code) isTaskExecPollResponse_ExitStatus() {}

func (*TaskExecPollResponse_Signal) isTaskExecPollResponse_ExitStatus() {}

type TaskExecStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	CommandArgs   []string               `protobuf:"bytes,3,rep,name=command_args,json=commandArgs,proto3" json:"command_args,omitempty"`
	StdoutConfig  TaskExecStdoutConfig   `protobuf:"varint,4,opt,name=stdout_config,json=stdoutConfig,proto3,enum=modal.task_command_router.TaskExecStdoutConfig" json:"stdout_config,omitempty"`
	StderrConfig  TaskExecStderrConfig   `protobuf:"varint,5,opt,name=stderr_config,json=stderrConfig,proto3,enum=modal.task_command_router.TaskExecStderrConfig" json:"stderr_config,omitempty"`
	TimeoutSecs   *uint32                `protobuf:"varint,6,opt,name=timeout_secs,json=timeoutSecs,proto3,oneof" json:"timeout_secs,omitempty"`
	Workdir       *string                `protobuf:"bytes,7,opt,name=workdir,proto3,oneof" json:"workdir,omitempty"`
	SecretIds     []string               `protobuf:"bytes,8,rep,name=secret_ids,json=secretIds,proto3" json:"secret_ids,omitempty"`
	PtyInfo       *PTYInfo               `protobuf:"bytes,9,opt,name=pty_info,json=ptyInfo,proto3,oneof" json:"pty_info,omitempty"`
	RuntimeDebug  bool                   `protobuf:"varint,10,opt,name=runtime_debug,json=runtimeDebug,proto3" json:"runtime_debug,omitempty"`
	ContainerId   string                 `protobuf:"bytes,11,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Env           map[string]string      `protobuf:"bytes,12,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecStartRequest) Reset() {
	*x = TaskExecStartRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStartRequest) ProtoMessage() {}

func (x *TaskExecStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecStartRequest.ProtoReflect.Descriptor instead.
func (*TaskExecStartRequest) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{2}
}

func (x *TaskExecStartRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecStartRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *TaskExecStartRequest) GetCommandArgs() []string {
	if x != nil {
		return x.CommandArgs
	}
	return nil
}

func (x *TaskExecStartRequest) GetStdoutConfig() TaskExecStdoutConfig {
	if x != nil {
		return x.StdoutConfig
	}
	return TaskExecStdoutConfig_TASK_EXEC_STDOUT_CONFIG_DEVNULL
}

func (x *TaskExecStartRequest) GetStderrConfig() TaskExecStderrConfig {
	if x != nil {
		return x.StderrConfig
	}
	return TaskExecStderrConfig_TASK_EXEC_STDERR_CONFIG_DEVNULL
}

func (x *TaskExecStartRequest) GetTimeoutSecs() uint32 {
	if x != nil && x.TimeoutSecs != nil {
		return *x.TimeoutSecs
	}
	return 0
}

func (x *TaskExecStartRequest) GetWorkdir() string {
	if x != nil && x.Workdir != nil {
		return *x.Workdir
	}
	return ""
}

func (x *TaskExecStartRequest) GetSecretIds() []string {
	if x != nil {
		return x.SecretIds
	}
	return nil
}

func (x *TaskExecStartRequest) GetPtyInfo() *PTYInfo {
	if x != nil {
		return x.PtyInfo
	}
	return nil
}

func (x *TaskExecStartRequest) GetRuntimeDebug() bool {
	if x != nil {
		return x.RuntimeDebug
	}
	return false
}

func (x *TaskExecStartRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *TaskExecStartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type TaskExecStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecStartResponse) Reset() {
	*x = TaskExecStartResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStartResponse) ProtoMessage() {}

func (x *TaskExecStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecStartResponse.ProtoReflect.Descriptor instead.
func (*TaskExecStartResponse) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{3}
}

type TaskExecStdioReadRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	TaskId         string                      `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecId         string                      `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Offset         uint64                      `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	FileDescriptor TaskExecStdioFileDescriptor `protobuf:"varint,4,opt,name=file_descriptor,json=fileDescriptor,proto3,enum=modal.task_command_router.TaskExecStdioFileDescriptor" json:"file_descriptor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskExecStdioReadRequest) Reset() {
	*x = TaskExecStdioReadRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdioReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdioReadRequest) ProtoMessage() {}

func (x *TaskExecStdioReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecStdioReadRequest.ProtoReflect.Descriptor instead.
func (*TaskExecStdioReadRequest) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{4}
}

func (x *TaskExecStdioReadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecStdioReadRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *TaskExecStdioReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TaskExecStdioReadRequest) GetFileDescriptor() TaskExecStdioFileDescriptor {
	if x != nil {
		return x.FileDescriptor
	}
	return TaskExecStdioFileDescriptor_TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT
}

type TaskExecStdioReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecStdioReadResponse) Reset() {
	*x = TaskExecStdioReadResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecStdioReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecStdioReadResponse) ProtoMessage() {}

func (x *TaskExecStdioReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecStdioReadResponse.ProtoReflect.Descriptor instead.
func (*TaskExecStdioReadResponse) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{5}
}

func (x *TaskExecStdioReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskExecWaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecWaitRequest) Reset() {
	*x = TaskExecWaitRequest{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecWaitRequest) ProtoMessage() {}

func (x *TaskExecWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecWaitRequest.ProtoReflect.Descriptor instead.
func (*TaskExecWaitRequest) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{6}
}

func (x *TaskExecWaitRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecWaitRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type TaskExecWaitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExitStatus:
	//
	//	*TaskExecWaitResponse_Code
	//	*TaskExecWaitResponse_Signal
	ExitStatus    isTaskExecWaitResponse_ExitStatus `protobuf_oneof:"exit_status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecWaitResponse) Reset() {
	*x = TaskExecWaitResponse{}
	mi := &file_modal_proto_task_command_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecWaitResponse) ProtoMessage() {}

func (x *TaskExecWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modal_proto_task_command_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecWaitResponse.ProtoReflect.Descriptor instead.
func (*TaskExecWaitResponse) Descriptor() ([]byte, []int) {
	return file_modal_proto_task_command_router_proto_rawDescGZIP(), []int{7}
}

func (x *TaskExecWaitResponse) GetExitStatus() isTaskExecWaitResponse_ExitStatus {
	if x != nil {
		return x.ExitStatus
	}
	return nil
}

func (x *TaskExecWaitResponse) GetCode() int32 {
	if x != nil {
		if x, ok := x.ExitStatus.(*TaskExecWaitResponse_Code); ok {
			return x.Code
		}
	}
	return 0
}

func (x *TaskExecWaitResponse) GetSignal() int32 {
	if x != nil {
		if x, ok := x.ExitStatus.(*TaskExecWaitResponse_Signal); ok {
			return x.Signal
		}
	}
	return 0
}

type isTaskExecWaitResponse_ExitStatus interface {
	isTaskExecWaitResponse_ExitStatus()
}

type TaskExecWaitResponse_Code struct {
	Code int32 `protobuf:"varint,1,opt,name=code,proto3,oneof"`
}

type TaskExecWaitResponse_Signal struct {
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof"`
}

func (*TaskExecWaitResponse_Code) isTaskExecWaitResponse_ExitStatus() {}

func (*TaskExecWaitResponse_Signal) isTaskExecWaitResponse_ExitStatus() {}

var File_modal_proto_task_command_router_proto protoreflect.FileDescriptor

const file_modal_proto_task_command_router_proto_rawDesc = "" +
	"\n" +
	"%modal_proto/task_command_router.proto\x12\x19modal.task_command_router\x1a\x15modal_proto/api.proto\"G\n" +
	"\x13TaskExecPollRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"U\n" +
	"\x14TaskExecPollResponse\x12\x14\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x12\x18\n" +
	"\x06signal\x18\x02 \x01(\x05H\x00R\x06signalB\r\n" +
	"\vexit_status\"\xaa\x05\n" +
	"\x14TaskExecStartRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12!\n" +
	"\fcommand_args\x18\x03 \x03(\tR\vcommandArgs\x12T\n" +
	"\rstdout_config\x18\x04 \x01(\x0e2/.modal.task_command_router.TaskExecStdoutConfigR\fstdoutConfig\x12T\n" +
	"\rstderr_config\x18\x05 \x01(\x0e2/.modal.task_command_router.TaskExecStderrConfigR\fstderrConfig\x12&\n" +
	"\ftimeout_secs\x18\x06 \x01(\rH\x00R\vtimeoutSecs\x88\x01\x01\x12\x1d\n" +
	"\aworkdir\x18\a \x01(\tH\x01R\aworkdir\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"secret_ids\x18\b \x03(\tR\tsecretIds\x125\n" +
	"\bpty_info\x18\t \x01(\v2\x15.modal.client.PTYInfoH\x02R\aptyInfo\x88\x01\x01\x12#\n" +
	"\rruntime_debug\x18\n" +
	" \x01(\bR\fruntimeDebug\x12!\n" +
	"\fcontainer_id\x18\v \x01(\tR\vcontainerId\x12J\n" +
	"\x03env\x18\f \x03(\v28.modal.task_command_router.TaskExecStartRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_timeout_secsB\n" +
	"\n" +
	"\b_workdirB\v\n" +
	"\t_pty_info\"\x17\n" +
	"\x15TaskExecStartResponse\"\xc5\x01\n" +
	"\x18TaskExecStdioReadRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12_\n" +
	"\x0ffile_descriptor\x18\x04 \x01(\x0e26.modal.task_command_router.TaskExecStdioFileDescriptorR\x0efileDescriptor\"/\n" +
	"\x19TaskExecStdioReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"G\n" +
	"\x13TaskExecWaitRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"U\n" +
	"\x14TaskExecWaitResponse\x12\x14\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x12\x18\n" +
	"\x06signal\x18\x02 \x01(\x05H\x00R\x06signalB\r\n" +
	"\vexit_status*\x81\x01\n" +
	"\x14TaskExecStderrConfig\x12#\n" +
	"\x1fTASK_EXEC_STDERR_CONFIG_DEVNULL\x10\x00\x12 \n" +
	"\x1cTASK_EXEC_STDERR_CONFIG_PIPE\x10\x01\x12\"\n" +
	"\x1eTASK_EXEC_STDERR_CONFIG_STDOUT\x10\x02*u\n" +
	"\x1bTaskExecStdioFileDescriptor\x12*\n" +
	"&TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDOUT\x10\x00\x12*\n" +
	"&TASK_EXEC_STDIO_FILE_DESCRIPTOR_STDERR\x10\x01*]\n" +
	"\x14TaskExecStdoutConfig\x12#\n" +
	"\x1fTASK_EXEC_STDOUT_CONFIG_DEVNULL\x10\x00\x12 \n" +
	"\x1cTASK_EXEC_STDOUT_CONFIG_PIPE\x10\x012\xec\x03\n" +
	"\x11TaskCommandRouter\x12r\n" +
	"\rTaskExecStart\x12/.modal.task_command_router.TaskExecStartRequest\x1a0.modal.task_command_router.TaskExecStartResponse\x12\x80\x01\n" +
	"\x11TaskExecStdioRead\x123.modal.task_command_router.TaskExecStdioReadRequest\x1a4.modal.task_command_router.TaskExecStdioReadResponse0\x01\x12o\n" +
	"\fTaskExecWait\x12..modal.task_command_router.TaskExecWaitRequest\x1a/.modal.task_command_router.TaskExecWaitResponse\x12o\n" +
	"\fTaskExecPoll\x12..modal.task_command_router.TaskExecPollRequest\x1a/.modal.task_command_router.TaskExecPollResponseB6Z4github.com/arugula-salad/wisp/frontend/modal/modalpbb\x06proto3"

var (
	file_modal_proto_task_command_router_proto_rawDescOnce sync.Once
	file_modal_proto_task_command_router_proto_rawDescData []byte
)

func file_modal_proto_task_command_router_proto_rawDescGZIP() []byte {
	file_modal_proto_task_command_router_proto_rawDescOnce.Do(func() {
		file_modal_proto_task_command_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modal_proto_task_command_router_proto_rawDesc), len(file_modal_proto_task_command_router_proto_rawDesc)))
	})
	return file_modal_proto_task_command_router_proto_rawDescData
}

var file_modal_proto_task_command_router_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_modal_proto_task_command_router_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_modal_proto_task_command_router_proto_goTypes = []any{
	(TaskExecStderrConfig)(0),         // 0: modal.task_command_router.TaskExecStderrConfig
	(TaskExecStdioFileDescriptor)(0),  // 1: modal.task_command_router.TaskExecStdioFileDescriptor
	(TaskExecStdoutConfig)(0),         // 2: modal.task_command_router.TaskExecStdoutConfig
	(*TaskExecPollRequest)(nil),       // 3: modal.task_command_router.TaskExecPollRequest
	(*TaskExecPollResponse)(nil),      // 4: modal.task_command_router.TaskExecPollResponse
	(*TaskExecStartRequest)(nil),      // 5: modal.task_command_router.TaskExecStartRequest
	(*TaskExecStartResponse)(nil),     // 6: modal.task_command_router.TaskExecStartResponse
	(*TaskExecStdioReadRequest)(nil),  // 7: modal.task_command_router.TaskExecStdioReadRequest
	(*TaskExecStdioReadResponse)(nil), // 8: modal.task_command_router.TaskExecStdioReadResponse
	(*TaskExecWaitRequest)(nil),       // 9: modal.task_command_router.TaskExecWaitRequest
	(*TaskExecWaitResponse)(nil),      // 10: modal.task_command_router.TaskExecWaitResponse
	nil,                               // 11: modal.task_command_router.TaskExecStartRequest.EnvEntry
	(*PTYInfo)(nil),                   // 12: modal.client.PTYInfo
}
var file_modal_proto_task_command_router_proto_depIdxs = []int32{
	2,  // 0: modal.task_command_router.TaskExecStartRequest.stdout_config:type_name -> modal.task_command_router.TaskExecStdoutConfig
	0,  // 1: modal.task_command_router.TaskExecStartRequest.stderr_config:type_name -> modal.task_command_router.TaskExecStderrConfig
	12, // 2: modal.task_command_router.TaskExecStartRequest.pty_info:type_name -> modal.client.PTYInfo
	11, // 3: modal.task_command_router.TaskExecStartRequest.env:type_name -> modal.task_command_router.TaskExecStartRequest.EnvEntry
	1,  // 4: modal.task_command_router.TaskExecStdioReadRequest.file_descriptor:type_name -> modal.task_command_router.TaskExecStdioFileDescriptor
	5,  // 5: modal.task_command_router.TaskCommandRouter.TaskExecStart:input_type -> modal.task_command_router.TaskExecStartRequest
	7,  // 6: modal.task_command_router.TaskCommandRouter.TaskExecStdioRead:input_type -> modal.task_command_router.TaskExecStdioReadRequest
	9,  // 7: modal.task_command_router.TaskCommandRouter.TaskExecWait:input_type -> modal.task_command_router.TaskExecWaitRequest
	3,  // 8: modal.task_command_router.TaskCommandRouter.TaskExecPoll:input_type -> modal.task_command_router.TaskExecPollRequest
	6,  // 9: modal.task_command_router.TaskCommandRouter.TaskExecStart:output_type -> modal.task_command_router.TaskExecStartResponse
	8,  // 10: modal.task_command_router.TaskCommandRouter.TaskExecStdioRead:output_type -> modal.task_command_router.TaskExecStdioReadResponse
	10, // 11: modal.task_command_router.TaskCommandRouter.TaskExecWait:output_type -> modal.task_command_router.TaskExecWaitResponse
	4,  // 12: modal.task_command_router.TaskCommandRouter.TaskExecPoll:output_type -> modal.task_command_router.TaskExecPollResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_modal_proto_task_command_router_proto_init() }
func file_modal_proto_task_command_router_proto_init() {
	if File_modal_proto_task_command_router_proto != nil {
		return
	}
	file_modal_proto_api_proto_init()
	file_modal_proto_task_command_router_proto_msgTypes[1].OneofWrappers = []any{
		(*TaskExecPollResponse_Code)(nil),
		(*TaskExecPollResponse_Signal)(nil),
	}
	file_modal_proto_task_command_router_proto_msgTypes[2].OneofWrappers = []any{}
	file_modal_proto_task_command_router_proto_msgTypes[7].OneofWrappers = []any{
		(*TaskExecWaitResponse_Code)(nil),
		(*TaskExecWaitResponse_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modal_proto_task_command_router_proto_rawDesc), len(file_modal_proto_task_command_router_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modal_proto_task_command_router_proto_goTypes,
		DependencyIndexes: file_modal_proto_task_command_router_proto_depIdxs,
		EnumInfos:         file_modal_proto_task_command_router_proto_enumTypes,
		MessageInfos:      file_modal_proto_task_command_router_proto_msgTypes,
	}.Build()
	File_modal_proto_task_command_router_proto = out.File
	file_modal_proto_task_command_router_proto_goTypes = nil
	file_modal_proto_task_command_router_proto_depIdxs = nil
}
